name: "BedFight"

version: 1.0.0-beta
api: 5.0.0

author: UnlimitedPowerHub
website: 'https://github.com/UnlimitedPowerHub/'

main: Amirreza\BedFight\BedFight

permissions:
  up.bf.use:
    default: true
  up.bf.op:
    default: op