name: "BedFight"

version: 1.0.0-beta
api: 5.0.0

author: UnlimitedPowerHub
website: 'https://github.com/UnlimitedPowerHub/'

main: up\Amirreza\BedFight\BedFight

commands:
  maplist:
    permission: use
  copymap:
    permission: use
  deletemap:
    permission: use
  tpworld:
    permission: use

permissions:
  use:
    default: true
  bedfight.use:
    default: true