<?php

declare(strict_types = 1);

namespace up\Amirreza\BedFight;

use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
use pocketmine\world\World;
use up\Amirreza\BedFight\Command\BedFightCommand;
use up\Amirreza\BedFight\Event\GameEvent;
use up\Amirreza\BedFight\Form\GameForm;
use up\Amirreza\BedFight\Form\SetUpForm;
use up\Amirreza\BedFight\Manager\GameManager;
use up\Amirreza\BedFight\Session\ArenaSession;
use up\Amirreza\BedFight\Session\GameSession;
use up\Amirreza\BedFight\Session\SetUpSession;
use up\Amirreza\BedFight\Storage\ArenaStorage;
use up\Amirreza\BedFight\Storage\GameStorage;

class BedFight extends PluginBase implements Listener {


    private static BedFight $instance;


    public null|World $LOBBY;


    private GameSession $gameSession;
    private ArenaSession $arenaSession;
    private SetUpSession $setUpSession;

    private GameStorage $gameStorage;

    private GameManager $gameManager;

    private GameForm $gameForm;
    private SetUpForm $setUpForm;
    private ArenaStorage $arenaStorage;


    public static function getInstance() : BedFight {
        return self::$instance;
    }

    protected function onLoad(): void
    {
        self::$instance = $this;
        $this->gameSession = new GameSession();
        $this->arenaSession = new ArenaSession();
        $this->setUpSession = new SetUpSession();
        $this->gameStorage = new GameStorage();
        $this->gameManager = new GameManager();
        $this->gameForm = new GameForm();
        $this->setUpForm = new SetupForm();
        $this->arenaStorage = new ArenaStorage();
        $this->LOBBY = $this->getServer()->getWorldManager()->getDefaultWorld();
        $this->getLogger()->info("BedFight loaded");
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        $this->getServer()->getPluginManager()->registerEvents(new GameEvent(), $this);
        $this->getServer()->getCommandMap()->register('bedfight',new BedFightCommand());
        $this->getLogger()->info("BedFight plugin enabled!");
        parent::onEnable(); // TODO: Change the autogenerated stub
    }


    public function getGameSession() : GameSession {
        return $this->gameSession;
    }

    public function getArenaSession() : ArenaSession {
        return $this->arenaSession;
    }

    public function getGameStorage() : GameStorage {
        return $this->gameStorage;
    }

    public function getGameManager() : GameManager {
        return $this->gameManager;
    }

    public function getGameForm() : GameForm {
        return $this->gameForm;
    }

    public function getSetUpSession() : SetUpSession {
        return $this->setUpSession;
    }

    public function getSetUpForm() : SetUpForm {
        return $this->setUpForm;
    }

    public function getArenaStorage() : ArenaStorage {
        return $this->arenaStorage;
    }

    protected function onDisable(): void
    {
        $this->getLogger()->info("BedFight plugin disabled!");
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

}