<?php

declare(strict_types = 1);

namespace up\Amirreza\BedFight;

use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
use pocketmine\world\World;
use up\Amirreza\BedFight\Event\GameEvent;
use up\Amirreza\BedFight\Manager\GameManager;
use up\Amirreza\BedFight\Session\GameSession;
use up\Amirreza\BedFight\Storage\GameStorage;
use up\Amirreza\BedFight\Command\BedFightCommand;

class BedFight extends PluginBase implements Listener {


    private static BedFight $instance;


    public null|World $LOBBY;


    private GameSession $gameSession;

    private GameStorage $gameStorage;

    private GameManager $gameManager;


    public static function getInstance() : BedFight {
        return self::$instance;
    }

    protected function onLoad(): void
    {
        self::$instance = $this;
        $this->gameSession = new GameSession();
        $this->gameStorage = new GameStorage();
        $this->gameManager = new GameManager();
        $this->LOBBY = $this->getServer()->getWorldManager()->getDefaultWorld();
        $this->getLogger()->info("BedFight loaded");
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        $this->getServer()->getPluginManager()->registerEvents(new GameEvent(), $this);
        $this->getServer()->getCommandMap()->register('bedfight',new BedFightCommand());
        $this->getLogger()->info("BedFight plugin enabled!");
        parent::onEnable(); // TODO: Change the autogenerated stub
    }


    public function getGameSession() : GameSession {
        return $this->gameSession;
    }

    public function getGameStorage() : GameStorage {
        return $this->gameStorage;
    }

    public function getGameManager() : GameManager {
        return $this->gameManager;
    }

    protected function onDisable(): void
    {
        $this->getLogger()->info("BedFight plugin disabled!");
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

}