<?php

namespace Amirreza\BedFight;

use pocketmine\plugin\PluginBase;
use Amirreza\BedFight\constant\BedFightConstant;

class BedFight extends PluginBase {

    private static BedFight $instance;

    public static function getInstance(): BedFight {
        return self::$instance;
    }

    protected function onLoad(): void
    {
        self::$instance = $this;
        $this->getLogger()->info(
            BedFightConstant::RBFFM . "Loaded!"
        );
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        BedFightHelper::init();
        $this->getLogger()->info(
            BedFightConstant::RBFFM."Enabled!"
        );
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    protected function onDisable(): void
    {
        $this->getLogger()->info(
            BedFightConstant::RBFFM."Disabled!"
        );
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}