<?php

namespace up\Amirreza\BF;

use pocketmine\plugin\PluginBase;
use up\Amirreza\BF\trait\CFUTrait;

class BFPluginBase extends PluginBase {

    use CFUTrait;

    private static BFPluginBase $instance;

    public static function getMe(): BFPluginBase {
        return self::$instance;
    }

    protected function onLoad(): void
    {
        self::$instance = $this;
        $this->getLogger()->info(
            self::RBFFM . "Loaded!"
        );
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        BFHelper::init();
        $this->getLogger()->info(
            self::RBFFM."Enabled!"
        );
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    protected function onDisable(): void
    {
        $this->getLogger()->info(
            self::RBFFM."Disabled!"
        );
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}